import type { SentenceEntry } from '../types';

export const sentences: SentenceEntry[] = [
  /* ──────────────────────────────────────────────────────────────────────────
   * EXERCISE 1 — Definite articles  (unit 1, examWeight 3)
   * ────────────────────────────────────────────────────────────────────────── */
  {
    id: 'exam-e1-1',
    kind: 'article',
    text: '____ ragazze sono in università a studiare.',
    answer: 'le',
    skills: ['article:def'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e1.1'],
  },
  {
    id: 'exam-e1-2',
    kind: 'article',
    text: "____ Italia è un paese molto bello.",
    answer: "l'",
    skills: ['article:def'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e1.2'],
  },
  {
    id: 'exam-e1-3',
    kind: 'article',
    text: 'Nel sud Italia ____ inverni non sono molto freddi.',
    answer: 'gli',
    skills: ['article:def'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e1.3'],
  },
  {
    id: 'exam-e1-4',
    kind: 'article',
    text: '____ fratelli di Giorgio sono molto alti.',
    answer: 'i',
    skills: ['article:def'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e1.4'],
  },
  {
    id: 'exam-e1-5',
    kind: 'article',
    text: 'Mi fa male ____ mano.',
    answer: 'la',
    skills: ['article:def'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e1.5'],
  },

  /* ──────────────────────────────────────────────────────────────────────────
   * EXERCISE 3 — essere / avere in context  (unit 1, examWeight 3)
   * ────────────────────────────────────────────────────────────────────────── */
  {
    id: 'exam-e3-1',
    kind: 'essere-avere',
    text: 'Se ____ caldo, potete aprire le finestre.',
    answer: 'avete',
    person: 'voi',
    gloss: 'avere caldo = tener calor',
    skills: ['avere', 'idiom:avere-caldo'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e3.1'],
  },
  {
    id: 'exam-e3-2',
    kind: 'essere-avere',
    text: 'Di dove ____ (voi)?',
    answer: 'siete',
    person: 'voi',
    skills: ['essere'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e3.2'],
  },
  {
    id: 'exam-e3-3',
    kind: 'essere-avere',
    text: 'La Sicilia e la Sardegna ____ le due grandi isole italiane.',
    answer: 'sono',
    person: 'loro',
    skills: ['essere'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e3.3'],
  },
  {
    id: 'exam-e3-4',
    kind: 'essere-avere',
    text: 'Giulia e Francesca ____ paura di arrivare tardi.',
    answer: 'hanno',
    person: 'loro',
    gloss: 'avere paura = tener miedo',
    skills: ['avere', 'idiom:avere-paura'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e3.4'],
  },
  {
    id: 'exam-e3-5',
    kind: 'essere-avere',
    text: 'Quante sorelle ____ (tu)?',
    answer: 'hai',
    person: 'tu',
    skills: ['avere'],
    unit: 1,
    examWeight: 3,
    source: ['exam:e3.5'],
  },

  /* ──────────────────────────────────────────────────────────────────────────
   * EXERCISE 4 — Conjugation from infinitive  (unit 2, examWeight 3)
   * ────────────────────────────────────────────────────────────────────────── */
  {
    id: 'exam-e4-1',
    kind: 'verb-conjugation',
    text: 'Io ____ sempre colazione alle 7:30.',
    lemma: 'fare',
    person: 'io',
    answer: 'faccio',
    skills: ['verb:fare', 'tense:presente', 'person:io'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.1'],
  },
  {
    id: 'exam-e4-2',
    kind: 'verb-conjugation',
    text: 'Tu ____ a scuola in autobus o a piedi?',
    lemma: 'andare',
    person: 'tu',
    answer: 'vai',
    skills: ['verb:andare', 'tense:presente', 'person:tu'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.2'],
  },
  {
    id: 'exam-e4-3',
    kind: 'verb-conjugation',
    text: 'Marco ____ i compiti prima di uscire.',
    lemma: 'fare',
    person: 'lui',
    answer: 'fa',
    skills: ['verb:fare', 'tense:presente', 'person:lui'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.3'],
  },
  {
    id: 'exam-e4-4',
    kind: 'verb-conjugation',
    text: 'Noi ____ a calcio ogni sabato pomeriggio.',
    lemma: 'giocare',
    person: 'noi',
    answer: 'giochiamo',
    skills: ['verb:giocare', 'tense:presente', 'person:noi'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.4'],
  },
  {
    id: 'exam-e4-5',
    kind: 'verb-conjugation',
    text: 'Tu ____ il conto in contanti o con la carta?',
    lemma: 'pagare',
    person: 'tu',
    answer: 'paghi',
    skills: ['verb:pagare', 'tense:presente', 'person:tu'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.5'],
  },
  {
    id: 'exam-e4-6',
    kind: 'verb-conjugation',
    text: 'Lucia e Marta ____ al cinema con noi stasera.',
    lemma: 'venire',
    person: 'loro',
    answer: 'vengono',
    skills: ['verb:venire', 'tense:presente', 'person:loro'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.6'],
  },
  {
    id: 'exam-e4-7',
    kind: 'verb-conjugation',
    text: 'Io ____ finire questo libro entro domani.',
    lemma: 'dovere',
    person: 'io',
    answer: 'devo',
    skills: ['verb:dovere', 'tense:presente', 'person:io'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.7'],
  },
  {
    id: 'exam-e4-8',
    kind: 'verb-conjugation',
    text: 'Tu non ____ uscire stasera, hai molto da studiare!',
    lemma: 'potere',
    person: 'tu',
    answer: 'puoi',
    skills: ['verb:potere', 'tense:presente', 'person:tu'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.8'],
  },
  {
    id: 'exam-e4-9',
    kind: 'verb-conjugation',
    text: 'Noi ____ partire presto per evitare il traffico.',
    lemma: 'volere',
    person: 'noi',
    answer: 'vogliamo',
    skills: ['verb:volere', 'tense:presente', 'person:noi'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.9'],
  },
  {
    id: 'exam-e4-10',
    kind: 'verb-conjugation',
    text: 'Loro ____ sempre i compiti prima di cena.',
    lemma: 'finire',
    person: 'loro',
    answer: 'finiscono',
    skills: ['verb:finire', 'tense:presente', 'person:loro'],
    unit: 2,
    examWeight: 3,
    source: ['exam:e4.10'],
  },

  /* ──────────────────────────────────────────────────────────────────────────
   * EXTRA PRACTICE — verb-conjugation  (examWeight 1)
   * ────────────────────────────────────────────────────────────────────────── */
  {
    id: 'extra-v1',
    kind: 'verb-conjugation',
    text: 'Marco e Lia ____ in autobus.',
    lemma: 'andare',
    person: 'loro',
    answer: 'vanno',
    skills: ['verb:andare', 'tense:presente', 'person:loro'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v2',
    kind: 'verb-conjugation',
    text: 'Voi ____ la pizza stasera?',
    lemma: 'fare',
    person: 'voi',
    answer: 'fate',
    skills: ['verb:fare', 'tense:presente', 'person:voi'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v3',
    kind: 'verb-conjugation',
    text: 'Io ____ al cinema con Anna.',
    lemma: 'venire',
    person: 'io',
    answer: 'vengo',
    skills: ['verb:venire', 'tense:presente', 'person:io'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v4',
    kind: 'verb-conjugation',
    text: 'Loro ____ a calcio il fine settimana.',
    lemma: 'giocare',
    person: 'loro',
    answer: 'giocano',
    skills: ['verb:giocare', 'tense:presente', 'person:loro'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v5',
    kind: 'verb-conjugation',
    text: 'Io ____ il caffè.',
    lemma: 'pagare',
    person: 'io',
    answer: 'pago',
    skills: ['verb:pagare', 'tense:presente', 'person:io'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v6',
    kind: 'verb-conjugation',
    text: 'Loro ____ sempre i compiti in anticipo.',
    lemma: 'finire',
    person: 'loro',
    answer: 'finiscono',
    skills: ['verb:finire', 'tense:presente', 'person:loro'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v7',
    kind: 'verb-conjugation',
    text: 'Lui ____ andare in vacanza quest\'estate.',
    lemma: 'volere',
    person: 'lui',
    answer: 'vuole',
    skills: ['verb:volere', 'tense:presente', 'person:lui'],
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'extra-v8',
    kind: 'verb-conjugation',
    text: 'Noi non ____ arrivare tardi.',
    lemma: 'potere',
    person: 'noi',
    answer: 'possiamo',
    skills: ['verb:potere', 'tense:presente', 'person:noi'],
    unit: 2,
    examWeight: 1,
  },

  /* ──────────────────────────────────────────────────────────────────────────
   * EXTRA PRACTICE — essere / avere  (examWeight 1)
   * ────────────────────────────────────────────────────────────────────────── */
  {
    id: 'extra-ea1',
    kind: 'essere-avere',
    text: 'Io ____ studente.',
    answer: 'sono',
    person: 'io',
    skills: ['essere'],
    unit: 1,
    examWeight: 1,
  },
  {
    id: 'extra-ea2',
    kind: 'essere-avere',
    text: 'Noi ____ fame dopo la lezione.',
    answer: 'abbiamo',
    person: 'noi',
    gloss: 'avere fame = tener hambre',
    skills: ['avere', 'idiom:avere-fame'],
    unit: 1,
    examWeight: 1,
  },
  {
    id: 'extra-ea3',
    kind: 'essere-avere',
    text: 'Tu ____ italiano?',
    answer: 'sei',
    person: 'tu',
    skills: ['essere'],
    unit: 1,
    examWeight: 1,
  },
];
