/**
 * time.ts — §10 «che ore sono?».
 *
 * Kind 'tell-time': el reloj se muestra como hero (texto), el alumno produce la
 * frase italiana. `answer` es la forma canónica «e + minutos»; `accept` recoge las
 * otras formas válidas (la forma «meno», la lectura de 24 h y variantes de
 * fracciones), porque para una hora abierta hay más de una respuesta correcta.
 * El validador es tolerante a acentos, así que è/é se aceptan como «near».
 */
import type { SentenceEntry } from '../types';

export const times: SentenceEntry[] = [
  {
    id: 'time-1-00',
    kind: 'tell-time',
    text: '1:00',
    answer: "è l'una",
    gloss: 'Es la una. Con l\'una/mezzogiorno/mezzanotte se usa «è» (no «sono le»).',
    skills: ['time', 'time:copula'],
    tags: ['rule:tell_time_copula'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-12-00',
    kind: 'tell-time',
    text: '12:00',
    answer: 'è mezzogiorno',
    accept: ['sono le dodici', 'è mezzogiorno in punto'],
    gloss: 'Es mediodía → è mezzogiorno (también «sono le dodici»).',
    skills: ['time', 'time:copula'],
    tags: ['rule:tell_time_copula'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-00-00',
    kind: 'tell-time',
    text: '00:00',
    answer: 'è mezzanotte',
    accept: ['sono le ventiquattro'],
    gloss: 'Es medianoche → è mezzanotte.',
    skills: ['time', 'time:copula'],
    tags: ['rule:tell_time_copula'],
    unit: 3,
    examWeight: 1,
  },
  {
    id: 'time-3-00',
    kind: 'tell-time',
    text: '3:00',
    answer: 'sono le tre',
    gloss: 'Son las tres → para las demás horas se usa «sono le …».',
    skills: ['time', 'time:copula'],
    tags: ['rule:tell_time_copula'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-7-10',
    kind: 'tell-time',
    text: '7:10',
    answer: 'sono le sette e dieci',
    gloss: 'Son las siete y diez → «e + minutos».',
    skills: ['time', 'time:minutes'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-3-15',
    kind: 'tell-time',
    text: '3:15',
    answer: 'sono le tre e un quarto',
    accept: ['sono le tre e quindici'],
    gloss: 'Las tres y cuarto → un quarto = 15.',
    skills: ['time', 'time:fractions'],
    tags: ['rule:tell_time_fractions'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-3-30',
    kind: 'tell-time',
    text: '3:30',
    answer: 'sono le tre e mezzo',
    accept: ['sono le tre e mezza', 'sono le tre e trenta'],
    gloss: 'Las tres y media → mezzo/mezza = 30.',
    skills: ['time', 'time:fractions'],
    tags: ['rule:tell_time_fractions'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-7-45',
    kind: 'tell-time',
    text: '7:45',
    answer: 'sono le otto meno un quarto',
    accept: ['sono le sette e quarantacinque', 'sono le otto meno quindici'],
    gloss: 'Las ocho menos cuarto → meno un quarto = 45 (también «le sette e quarantacinque»).',
    skills: ['time', 'time:fractions'],
    tags: ['rule:tell_time_fractions'],
    unit: 3,
    examWeight: 2,
  },
  {
    id: 'time-4-48',
    kind: 'tell-time',
    text: '4:48',
    answer: 'sono le quattro e quarantotto',
    accept: ['sono le cinque meno dodici'],
    gloss: 'Dos formas válidas: «le quattro e quarantotto» o «le cinque meno dodici».',
    skills: ['time', 'time:minutes'],
    unit: 3,
    examWeight: 1,
  },
  {
    id: 'time-19-45',
    kind: 'tell-time',
    text: '19:45',
    answer: 'sono le otto meno un quarto',
    accept: [
      'sono le sette e quarantacinque',
      'sono le diciannove e quarantacinque',
    ],
    gloss: '24 h: las 19:45 → «le otto meno un quarto» / «le diciannove e quarantacinque».',
    skills: ['time', 'time:24h'],
    tags: ['rule:tell_time_fractions'],
    unit: 3,
    examWeight: 1,
  },
];
