import type { VocabEntry } from '../types';

/**
 * Body parts vocabulary (Unit 2, Exam Ex7).
 *
 * The 10 EXAM terms (examWeight: 3) + 8 extras (examWeight: 1) — each in whichever
 * number the exam/book used. Every one of those 18 also gets a companion entry
 * (examWeight: 1) in the OTHER number, so both singular and plural are quizzed for
 * every word (several are irregular: braccio/braccia, dito/dita, labbro/labbra
 * switch to feminine in the plural; orecchio's common plural is fem. "le orecchie").
 * All category: 'body'. Glosses are ES-MX.
 */
export const vocab: VocabEntry[] = [
  // ────────────────────────────────────────────────────────────────────────────
  // 10 EXAM terms (examWeight: 3) + their singular/plural companion
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: 'capelli',
    term: 'capelli',
    gloss: 'el cabello / el pelo',
    category: 'body',
    gender: 'm',
    article: 'i',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'capello',
    term: 'capello',
    gloss: 'un cabello / un pelo',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'occhi',
    term: 'occhi',
    gloss: 'los ojos',
    category: 'body',
    gender: 'm',
    article: 'gli',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'occhio',
    term: 'occhio',
    gloss: 'el ojo',
    category: 'body',
    gender: 'm',
    article: "l'",
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'naso',
    term: 'naso',
    gloss: 'la nariz',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'nasi',
    term: 'nasi',
    gloss: 'las narices',
    category: 'body',
    gender: 'm',
    article: 'i',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'collo',
    term: 'collo',
    gloss: 'el cuello',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'colli',
    term: 'colli',
    gloss: 'los cuellos',
    category: 'body',
    gender: 'm',
    article: 'i',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'braccio',
    term: 'braccio',
    gloss: 'el brazo',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'braccia',
    term: 'braccia',
    gloss: 'los brazos',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'gamba',
    term: 'gamba',
    gloss: 'la pierna',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'gambe',
    term: 'gambe',
    gloss: 'las piernas',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'piedi',
    term: 'piedi',
    gloss: 'los pies',
    category: 'body',
    gender: 'm',
    article: 'i',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'piede',
    term: 'piede',
    gloss: 'el pie',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'bocca',
    term: 'bocca',
    gloss: 'la boca',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'bocche',
    term: 'bocche',
    gloss: 'las bocas',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'pancia',
    term: 'pancia',
    gloss: 'la panza / la barriga',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'pance',
    term: 'pance',
    gloss: 'las panzas / las barrigas',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'mano',
    term: 'mano',
    gloss: 'la mano',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 3,
  },
  {
    id: 'mani',
    term: 'mani',
    gloss: 'las manos',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  // ────────────────────────────────────────────────────────────────────────────
  // 8 EXTRAS (examWeight: 1) + their singular/plural companion
  // ────────────────────────────────────────────────────────────────────────────

  {
    id: 'orecchio',
    term: 'orecchio',
    gloss: 'la oreja',
    category: 'body',
    gender: 'm',
    article: "l'",
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'orecchie',
    term: 'orecchie',
    gloss: 'las orejas',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'denti',
    term: 'denti',
    gloss: 'los dientes',
    category: 'body',
    gender: 'm',
    article: 'i',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'dente',
    term: 'dente',
    gloss: 'el diente',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'labbra',
    term: 'labbra',
    gloss: 'los labios',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'labbro',
    term: 'labbro',
    gloss: 'el labio',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'fronte',
    term: 'fronte',
    gloss: 'la frente',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'fronti',
    term: 'fronti',
    gloss: 'las frentes',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'spalla',
    term: 'spalla',
    gloss: 'el hombro',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'spalle',
    term: 'spalle',
    gloss: 'los hombros',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'dito',
    term: 'dito',
    gloss: 'el dedo',
    category: 'body',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'dita',
    term: 'dita',
    gloss: 'los dedos',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'testa',
    term: 'testa',
    gloss: 'la cabeza',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'teste',
    term: 'teste',
    gloss: 'las cabezas',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  {
    id: 'faccia',
    term: 'faccia',
    gloss: 'la cara',
    category: 'body',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 1,
  },
  {
    id: 'facce',
    term: 'facce',
    gloss: 'las caras',
    category: 'body',
    gender: 'f',
    article: 'le',
    unit: 2,
    examWeight: 1,
  },

  // ────────────────────────────────────────────────────────────────────────────
  // Días de la semana (brief §9). lunedì–venerdì llevan -ì acentuada (tolerada por
  // el validador como "near"); todos masculinos salvo domenica (femenino).
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: 'lunedì',
    term: 'lunedì',
    gloss: 'el lunes',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'martedì',
    term: 'martedì',
    gloss: 'el martes',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'mercoledì',
    term: 'mercoledì',
    gloss: 'el miércoles',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'giovedì',
    term: 'giovedì',
    gloss: 'el jueves',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'venerdì',
    term: 'venerdì',
    gloss: 'el viernes',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'sabato',
    term: 'sabato',
    gloss: 'el sábado',
    category: 'days',
    gender: 'm',
    article: 'il',
    unit: 2,
    examWeight: 2,
  },
  {
    id: 'domenica',
    term: 'domenica',
    gloss: 'el domingo',
    category: 'days',
    gender: 'f',
    article: 'la',
    unit: 2,
    examWeight: 2,
  },
];
