window.WORDS = [
  { groupId: "problema", word: "problema", translation: "problema", definite: "il", gender: "m", number: "singular", rule: "greek_ma" },
  { groupId: "problema", word: "problemi", translation: "problemas", definite: "i", gender: "m", number: "plural", rule: "greek_ma" },
  { groupId: "cinema", word: "cinema", translation: "cine", definite: "il", gender: "m", number: "singular", rule: "greek_ma_invariable" },
  { groupId: "cinema", word: "cinema", translation: "cines", definite: "i", gender: "m", number: "plural", rule: "greek_ma_invariable" },
  { groupId: "programma", word: "programma", translation: "programa", definite: "il", gender: "m", number: "singular", rule: "greek_ma" },
  { groupId: "programma", word: "programmi", translation: "programas", definite: "i", gender: "m", number: "plural", rule: "greek_ma" },
  { groupId: "sistema", word: "sistema", translation: "sistema", definite: "il", gender: "m", number: "singular", rule: "greek_ma" },
  { groupId: "sistema", word: "sistemi", translation: "sistemas", definite: "i", gender: "m", number: "plural", rule: "greek_ma" },
  { groupId: "mano", word: "mano", translation: "mano", definite: "la", gender: "f", number: "singular", rule: "fem_o_irregular" },
  { groupId: "mano", word: "mani", translation: "manos", definite: "le", gender: "f", number: "plural", rule: "fem_o_irregular" },
  { groupId: "foto", word: "foto", translation: "foto", definite: "la", gender: "f", number: "singular", rule: "fem_o_invariable" },
  { groupId: "foto", word: "foto", translation: "fotos", definite: "le", gender: "f", number: "plural", rule: "fem_o_invariable" },
  { groupId: "moto", word: "moto", translation: "moto", definite: "la", gender: "f", number: "singular", rule: "fem_o_invariable" },
  { groupId: "moto", word: "moto", translation: "motos", definite: "le", gender: "f", number: "plural", rule: "fem_o_invariable" },
  { groupId: "citta", word: "città", translation: "ciudad", definite: "la", gender: "f", number: "singular", rule: "accented_invariable" },
  { groupId: "citta", word: "città", translation: "ciudades", definite: "le", gender: "f", number: "plural", rule: "accented_invariable" },
  { groupId: "universita", word: "università", translation: "universidad", definite: "l'", gender: "f", number: "singular", rule: "vowel_f_accented" },
  { groupId: "universita", word: "università", translation: "universidades", definite: "le", gender: "f", number: "plural", rule: "accented_invariable" },
  { groupId: "studente", word: "studente", translation: "estudiante", definite: "lo", gender: "m", number: "singular", rule: "s_consonant" },
  { groupId: "studente", word: "studenti", translation: "estudiantes", definite: "gli", gender: "m", number: "plural", rule: "s_consonant" },
  { groupId: "zaino", word: "zaino", translation: "mochila", definite: "lo", gender: "m", number: "singular", rule: "z_start" },
  { groupId: "zaino", word: "zaini", translation: "mochilas", definite: "gli", gender: "m", number: "plural", rule: "z_start" },
  { groupId: "specchio", word: "specchio", translation: "espejo", definite: "lo", gender: "m", number: "singular", rule: "s_consonant" },
  { groupId: "specchio", word: "specchi", translation: "espejos", definite: "gli", gender: "m", number: "plural", rule: "s_consonant" },
  { groupId: "sbaglio", word: "sbaglio", translation: "error", definite: "lo", gender: "m", number: "singular", rule: "s_consonant" },
  { groupId: "sbaglio", word: "sbagli", translation: "errores", definite: "gli", gender: "m", number: "plural", rule: "s_consonant" },
  { groupId: "sport", word: "sport", translation: "deporte", definite: "lo", gender: "m", number: "singular", rule: "foreign_s_consonant" },
  { groupId: "sport", word: "sport", translation: "deportes", definite: "gli", gender: "m", number: "plural", rule: "foreign_s_consonant" },
  { groupId: "smartwatch", word: "smartwatch", translation: "reloj inteligente", definite: "lo", gender: "m", number: "singular", rule: "foreign_s_consonant" },
  { groupId: "smartwatch", word: "smartwatch", translation: "relojes inteligentes", definite: "gli", gender: "m", number: "plural", rule: "foreign_s_consonant" },
  { groupId: "stivale", word: "stivale", translation: "bota", definite: "lo", gender: "m", number: "singular", rule: "s_consonant" },
  { groupId: "stivale", word: "stivali", translation: "botas", definite: "gli", gender: "m", number: "plural", rule: "s_consonant" },
  { groupId: "zio", word: "zio", translation: "tío", definite: "lo", gender: "m", number: "singular", rule: "z_start" },
  { groupId: "zio", word: "zii", translation: "tíos", definite: "gli", gender: "m", number: "plural", rule: "z_start" },
  { groupId: "zucchero", word: "zucchero", translation: "azúcar", definite: "lo", gender: "m", number: "singular", rule: "z_start" },
  { groupId: "zucchero", word: "zuccheri", translation: "azúcares", definite: "gli", gender: "m", number: "plural", rule: "z_start" },
  { groupId: "zoo", word: "zoo", translation: "zoológico", definite: "lo", gender: "m", number: "singular", rule: "z_start_invariable" },
  { groupId: "zoo", word: "zoo", translation: "zoológicos", definite: "gli", gender: "m", number: "plural", rule: "z_start_invariable" },
  { groupId: "zainetto", word: "zainetto", translation: "mochila pequeña", definite: "lo", gender: "m", number: "singular", rule: "z_start" },
  { groupId: "zainetto", word: "zainetti", translation: "mochilas pequeñas", definite: "gli", gender: "m", number: "plural", rule: "z_start" },
  { groupId: "gnocco", word: "gnocco", translation: "ñoqui", definite: "lo", gender: "m", number: "singular", rule: "gn_start" },
  { groupId: "gnocco", word: "gnocchi", translation: "ñoquis", definite: "gli", gender: "m", number: "plural", rule: "gn_start" },
  { groupId: "gnomo", word: "gnomo", translation: "gnomo", definite: "lo", gender: "m", number: "singular", rule: "gn_start" },
  { groupId: "gnomo", word: "gnomi", translation: "gnomos", definite: "gli", gender: "m", number: "plural", rule: "gn_start" },
  { groupId: "gnu", word: "gnu", translation: "ñu", definite: "lo", gender: "m", number: "singular", rule: "gn_start_invariable" },
  { groupId: "gnu", word: "gnu", translation: "ñus", definite: "gli", gender: "m", number: "plural", rule: "gn_start_invariable" },
  { groupId: "psicologo", word: "psicologo", translation: "psicólogo", definite: "lo", gender: "m", number: "singular", rule: "ps_start" },
  { groupId: "psicologo", word: "psicologi", translation: "psicólogos", definite: "gli", gender: "m", number: "plural", rule: "ps_start" },
  { groupId: "pseudonimo", word: "pseudonimo", translation: "pseudónimo", definite: "lo", gender: "m", number: "singular", rule: "ps_start" },
  { groupId: "pseudonimo", word: "pseudonimi", translation: "pseudónimos", definite: "gli", gender: "m", number: "plural", rule: "ps_start" },
  { groupId: "pneumatico", word: "pneumatico", translation: "neumático", definite: "lo", gender: "m", number: "singular", rule: "pn_start" },
  { groupId: "pneumatico", word: "pneumatici", translation: "neumáticos", definite: "gli", gender: "m", number: "plural", rule: "pn_start" },
  { groupId: "xilofono", word: "xilofono", translation: "xilófono", definite: "lo", gender: "m", number: "singular", rule: "x_start" },
  { groupId: "xilofono", word: "xilofoni", translation: "xilófonos", definite: "gli", gender: "m", number: "plural", rule: "x_start" },
  { groupId: "yogurt", word: "yogurt", translation: "yogur", definite: "lo", gender: "m", number: "singular", rule: "y_start_invariable" },
  { groupId: "yogurt", word: "yogurt", translation: "yogures", definite: "gli", gender: "m", number: "plural", rule: "y_start_invariable" },
  { groupId: "yoga", word: "yoga", translation: "yoga", definite: "lo", gender: "m", number: "singular", rule: "y_start_invariable" },
  { groupId: "yoga", word: "yoga", translation: "yogas", definite: "gli", gender: "m", number: "plural", rule: "y_start_invariable" },
  { groupId: "amico", word: "amico", translation: "amigo", definite: "l'", gender: "m", number: "singular", rule: "vowel_m" },
  { groupId: "amico", word: "amici", translation: "amigos", definite: "gli", gender: "m", number: "plural", rule: "vowel_m" },
  { groupId: "albero", word: "albero", translation: "árbol", definite: "l'", gender: "m", number: "singular", rule: "vowel_m" },
  { groupId: "albero", word: "alberi", translation: "árboles", definite: "gli", gender: "m", number: "plural", rule: "vowel_m" },
  { groupId: "orologio", word: "orologio", translation: "reloj", definite: "l'", gender: "m", number: "singular", rule: "vowel_m" },
  { groupId: "orologio", word: "orologi", translation: "relojes", definite: "gli", gender: "m", number: "plural", rule: "vowel_m" },
  { groupId: "anno", word: "anno", translation: "año", definite: "l'", gender: "m", number: "singular", rule: "vowel_m" },
  { groupId: "anno", word: "anni", translation: "años", definite: "gli", gender: "m", number: "plural", rule: "vowel_m" },
  { groupId: "aeroporto", word: "aeroporto", translation: "aeropuerto", definite: "l'", gender: "m", number: "singular", rule: "vowel_m" },
  { groupId: "aeroporto", word: "aeroporti", translation: "aeropuertos", definite: "gli", gender: "m", number: "plural", rule: "vowel_m" },
  { groupId: "uomo", word: "uomo", translation: "hombre", definite: "l'", gender: "m", number: "singular", rule: "vowel_m_irregular" },
  { groupId: "uomo", word: "uomini", translation: "hombres", definite: "gli", gender: "m", number: "plural", rule: "vowel_m_irregular" },
  { groupId: "amica", word: "amica", translation: "amiga", definite: "l'", gender: "f", number: "singular", rule: "vowel_f" },
  { groupId: "amica", word: "amiche", translation: "amigas", definite: "le", gender: "f", number: "plural", rule: "vowel_f" },
  { groupId: "isola", word: "isola", translation: "isla", definite: "l'", gender: "f", number: "singular", rule: "vowel_f" },
  { groupId: "isola", word: "isole", translation: "islas", definite: "le", gender: "f", number: "plural", rule: "vowel_f" },
  { groupId: "arte", word: "arte", translation: "arte", definite: "l'", gender: "f", number: "singular", rule: "vowel_f" },
  { groupId: "arte", word: "arti", translation: "artes", definite: "le", gender: "f", number: "plural", rule: "vowel_f" },
  { groupId: "ora", word: "ora", translation: "hora", definite: "l'", gender: "f", number: "singular", rule: "vowel_f" },
  { groupId: "ora", word: "ore", translation: "horas", definite: "le", gender: "f", number: "plural", rule: "vowel_f" },
  { groupId: "idea", word: "idea", translation: "idea", definite: "l'", gender: "f", number: "singular", rule: "vowel_f" },
  { groupId: "idea", word: "idee", translation: "ideas", definite: "le", gender: "f", number: "plural", rule: "vowel_f" },
  { groupId: "libro", word: "libro", translation: "libro", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "libro", word: "libri", translation: "libros", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "cane", word: "cane", translation: "perro", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "cane", word: "cani", translation: "perros", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "fiore", word: "fiore", translation: "flor", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "fiore", word: "fiori", translation: "flores", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "giorno", word: "giorno", translation: "día", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "giorno", word: "giorni", translation: "días", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "ragazzo", word: "ragazzo", translation: "chico", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "ragazzo", word: "ragazzi", translation: "chicos", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "fratello", word: "fratello", translation: "hermano", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "fratello", word: "fratelli", translation: "hermanos", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "treno", word: "treno", translation: "tren", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "treno", word: "treni", translation: "trenes", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "ristorante", word: "ristorante", translation: "restaurante", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "ristorante", word: "ristoranti", translation: "restaurantes", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "caffe", word: "caffè", translation: "café", definite: "il", gender: "m", number: "singular", rule: "truncated_accented" },
  { groupId: "caffe", word: "caffè", translation: "cafés", definite: "i", gender: "m", number: "plural", rule: "truncated_accented" },
  { groupId: "gatto", word: "gatto", translation: "gato", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "gatto", word: "gatti", translation: "gatos", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "tavolo", word: "tavolo", translation: "mesa", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "tavolo", word: "tavoli", translation: "mesas", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "letto", word: "letto", translation: "cama", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "letto", word: "letti", translation: "camas", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "bagno", word: "bagno", translation: "baño", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "bagno", word: "bagni", translation: "baños", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "vestito", word: "vestito", translation: "ropa", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "vestito", word: "vestiti", translation: "ropas", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "biglietto", word: "biglietto", translation: "boleto", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "biglietto", word: "biglietti", translation: "boletos", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "negozio", word: "negozio", translation: "tienda", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "negozio", word: "negozi", translation: "tiendas", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "medico", word: "medico", translation: "médico", definite: "il", gender: "m", number: "singular", rule: null },
  { groupId: "medico", word: "medici", translation: "médicos", definite: "i", gender: "m", number: "plural", rule: null },
  { groupId: "casa", word: "casa", translation: "casa", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "casa", word: "case", translation: "casas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "scuola", word: "scuola", translation: "escuela", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "scuola", word: "scuole", translation: "escuelas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "notte", word: "notte", translation: "noche", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "notte", word: "notti", translation: "noches", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "chiave", word: "chiave", translation: "llave", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "chiave", word: "chiavi", translation: "llaves", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "ragazza", word: "ragazza", translation: "chica", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "ragazza", word: "ragazze", translation: "chicas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "donna", word: "donna", translation: "mujer", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "donna", word: "donne", translation: "mujeres", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "sorella", word: "sorella", translation: "hermana", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "sorella", word: "sorelle", translation: "hermanas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "macchina", word: "macchina", translation: "coche", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "macchina", word: "macchine", translation: "coches", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "parola", word: "parola", translation: "palabra", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "parola", word: "parole", translation: "palabras", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "sedia", word: "sedia", translation: "silla", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "sedia", word: "sedie", translation: "sillas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "porta", word: "porta", translation: "puerta", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "porta", word: "porte", translation: "puertas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "finestra", word: "finestra", translation: "ventana", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "finestra", word: "finestre", translation: "ventanas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "scarpa", word: "scarpa", translation: "zapato", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "scarpa", word: "scarpe", translation: "zapatos", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "borsa", word: "borsa", translation: "bolso", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "borsa", word: "borse", translation: "bolsos", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "domanda", word: "domanda", translation: "pregunta", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "domanda", word: "domande", translation: "preguntas", definite: "le", gender: "f", number: "plural", rule: null },
  { groupId: "risposta", word: "risposta", translation: "respuesta", definite: "la", gender: "f", number: "singular", rule: null },
  { groupId: "risposta", word: "risposte", translation: "respuestas", definite: "le", gender: "f", number: "plural", rule: null }
];

window.EXPLANATION_RULES = {
  greek_ma: { title: "Origen griego (-ma)", text: "Termina en **-a**, pero es **masculino**. En plural cambia a **-i**: **il problema -> i problemi**." },
  greek_ma_invariable: { title: "Origen griego invariable", text: "Masculino terminado en **-a** que **no cambia en plural**. El artículo marca el número: **il cinema -> i cinema**." },
  fem_o_irregular: { title: "Femenino irregular en -o", text: "Es **femenino** aunque termina en **-o**. El plural mantiene artículo femenino: **la mano -> le mani**." },
  fem_o_invariable: { title: "Femenino abreviado", text: "Viene de una forma reducida, como **fotografia -> foto**. Es **femenino e invariable**: **la foto -> le foto**." },
  accented_invariable: { title: "Acentuada invariable", text: "Las palabras con **vocal final acentuada** no cambian en plural: **la città -> le città**." },
  s_consonant: { title: "S + consonante", text: "Los masculinos con **s + consonante** usan **lo** en singular y **gli** en plural." },
  foreign_s_consonant: { title: "Préstamo con s + consonante", text: "Palabra extranjera con **s + consonante**. Usa **lo / gli** y suele ser **invariable**." },
  z_start: { title: "Empieza con z", text: "Los masculinos que **empiezan con z** usan **lo** en singular y **gli** en plural." },
  z_start_invariable: { title: "Z invariable", text: "Empieza con **z** y **no cambia en plural**. El artículo marca el número: **lo zoo -> gli zoo**." },
  gn_start: { title: "Empieza con gn", text: "Los masculinos que **empiezan con gn** usan **lo** en singular y **gli** en plural." },
  gn_start_invariable: { title: "GN invariable", text: "Empieza con **gn** y **no cambia en plural**. El artículo marca el número: **lo gnu -> gli gnu**." },
  ps_start: { title: "Empieza con ps", text: "Los masculinos que **empiezan con ps** usan **lo** en singular y **gli** en plural." },
  pn_start: { title: "Empieza con pn", text: "Los masculinos que **empiezan con pn** usan **lo** en singular y **gli** en plural." },
  x_start: { title: "Empieza con x", text: "Los masculinos que **empiezan con x** usan **lo** en singular y **gli** en plural." },
  y_start_invariable: { title: "Empieza con y", text: "Los masculinos con **y de sonido consonántico** usan **lo / gli** y suelen ser **invariables**." },
  vowel_m: { title: "Elisión masculina", text: "Los masculinos con **vocal** usan **l'** en singular, pero **gli** en plural: **l'amico -> gli amici**." },
  vowel_m_irregular: { title: "Plural irregular con vocal", text: "La raíz **cambia en plural**, pero el artículo sigue la regla de vocal: **l'uomo -> gli uomini**." },
  vowel_f: { title: "Elisión femenina", text: "Los femeninos con **vocal** usan **l'** en singular y **le** en plural: **l'amica -> le amiche**." },
  vowel_f_accented: { title: "Elisión femenina acentuada", text: "Empieza con **vocal** y termina con **acento**. En singular usa **l'** y en plural **le**: **l'università -> le università**." },
  truncated_accented: { title: "Masculino acentuado invariable", text: "Masculino con **acento final**. No cambia en plural: **il caffè -> i caffè**." }
};
